name: Krishi Fagwani
favicon: null
layout_spectrum: 0.4308105455711484
typography_spectrum: 0.26096294331364334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.565652595134452
  lightness: 0.07298226980492473
  saturation: 0.4933876311406493
  rhythmicContrast: 0.5107991539407521
purpose: []
